### ISSUE TITLE
German inflections of verbs

### ISSUE THREAD

**Issue by Vinesid** [dkpro/dkpro-jwktl#27]
Hi,
i'm trying to get the inflections of verbs. For example "reden" https://de.wiktionary.org/wiki/reden
Now i want to know the first person simple present form of "reden". When you check the site and the table on it you see, that it should be "ich rede".

I'm expecting that the method `getWordForms()` will do this, nut unfortunally i get on all german verbs `null`. On nouns (example "Auto" https://de.wiktionary.org/wiki/Auto) i recieve the different forms like "des Autos". What method do i have to call, to get the inflection of a verb?

**Comment by chmeyer** [comment]
Different inflection templates are used in Wiktionary. The one used for "reden" is "Deutsch Verb Übersicht". Added support for this template.

**Comment by Vinesid** [comment]
Great thanks.
When will version 1.1.0 (or 1.0.2) be available in maven?
