### ISSUE TITLE
Is a pre-built JWKTL database dump available?

### ISSUE THREAD

**Issue by josephrocca** [dkpro/dkpro-jwktl#32]
Hi, sorry to post this as an issue, but I figured this would be the best form of communication. I'm wondering whether there are any dumps of the scraped data available which I can play around with? I'd really love to use this project, but am hesitant to learn Java and troubleshoot my way to creating my own database without knowing whether it'll be useful for my purposes.

Thanks for your team's work on this!

**Comment by chmeyer** [comment]
Unfortunately, there are currently no public dumps. However, the dumps are using a quite specific data format anyway, so it is highly recommended to access it with the API - and having the API running should make it easy to parse a dump as well, just make sure to set enough memory.
