### ISSUE TITLE
English word forms

### ISSUE THREAD

**Issue by prohit93** [dkpro/dkpro-jwktl#45]
I am using the EnglishWordFormHandler for generating the word forms for verb lemmas. 
How ever I am confused on how to use the Template object which is required for this task.
I am setting the name of the template object as "en-verb", and I am unable to understand what the parameters to this template object should be. Can you please help me here?
Thank you.

**Comment by chmeyer** [comment]
The `Template` objects model wiki-markup templates. That is, text segments of the raw Wiktionary article  that are enclosed in two curly brackets. For example, `{{audio|en-us-run.ogg|Audio (US)|lang=en}}` in the article `run`, which yields a link to a pronunciation file. The template consists of a name ("audio") and multiple parameters, which are either named ("lang=en") or unnamed ("en-us-run.ogg"). The `Template` class lets you access these properties using `getName()`, `getNumberedParam()`and `getNamedParam()`. The `Template` objects are typically generated using the `TemplateParser`.

Mind if you only want to access Wiktionary data, run the parser first (following the example code on the JWKTL homepage) and then use, e.g., `IWiktionaryEntry.getWordForms()` to access inflected verb forms. You won't need to parse templates then.
