### ISSUE TITLE
Retrieve data in different language than query string?

### ISSUE THREAD

**Issue by rraallvv** [dkpro/dkpro-jwktl#47]
I'd come in handy if one could specify a different language for the definitions than the one used for the query string, a bit like a translator.

So for instance, when I want some translation for a word, I go to the Wiktionary search for that word's definition and then click the language I'm interested in.

Is this supported by JWKTL, or by the Wiktionary API for that matter.

**Comment by chmeyer** [comment]
This is not supported right away, but you can easily built this by calling the API functions (i.e., retrieve the entry in one language, look up its translations choosing the target language of your choice, and then looking up this word in the target language). Mind that Wiktionary does not disambiguate the translation targets. In a different project, we tried several scientific methods for this goal, see https://www.ukp.tu-darmstadt.de/data/lexical-resources/wiktionary/ontowiktionary/ and https://www.ukp.tu-darmstadt.de/data/lexical-resources/wiktionary/multilingual-sense-disambiguated-wiktionary/

**Comment by rraallvv** [comment]
@chmeyer thanks for the information, it's very much appreciated.
